# Docker-specific configuration for persistent deployment
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
        - SANDBOX_PROVIDER=${SANDBOX_PROVIDER:-e2b}
        - E2B_API_KEY=${E2B_API_KEY}
        - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - GEMINI_API_KEY=${GEMINI_API_KEY}
        - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      # Persistent storage for sandbox state
      - sandbox-data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    env_file:
      - .env.docker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=openlovable
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  sandbox-data:
  postgres-data:
  redis-data: